import React, { useState, useEffect } from 'react';
import { recommendationService } from '../../services/recommendationService';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { Badge } from '../../components/common/Badge';
import { Sparkles, Server } from 'lucide-react';

export const RecommendationsPage = () => {
  const [recommendations, setRecommendations] = useState([]);
  const [loading, setLoading] = useState(true);

  const loadData = async () => {
    setLoading(true);
    try {
      const recData = await recommendationService.getRecommendations();
      setRecommendations(recData || []);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, []);

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <h2 className="text-xl sm:text-2xl font-extrabold text-slate-100 tracking-tight">
              Sustainability Recommendations
            </h2>
            <Badge variant="emerald">VESIT Decarbonization Advisory</Badge>
          </div>
          <p className="text-xs text-slate-400 mt-1">
            Actionable energy efficiency and carbon reduction strategies customized to VESIT campus facilities.
          </p>
        </div>
        <button onClick={loadData} className="px-4 py-2 bg-brand-600 text-white rounded-xl text-xs font-bold hover:bg-brand-500 transition-colors shadow-lg shadow-brand-900/30">
          Refresh Recommendations
        </button>
      </div>

      {loading ? (
        <LoadingSpinner size="lg" text="Synthesizing Campus Decarbonization Recommendations..." className="min-h-[40vh]" />
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
          {recommendations.map((rec) => (
            <div
              key={rec.id}
              className={`glass-card rounded-2xl p-5 border flex flex-col justify-between transition-all ${
                rec.priority === 'HIGH'
                  ? 'border-rose-500/30 hover:border-rose-500/50 bg-gradient-to-br from-rose-950/10 to-slate-900'
                  : rec.priority === 'MEDIUM'
                  ? 'border-amber-500/30 hover:border-amber-500/50 bg-gradient-to-br from-amber-950/10 to-slate-900'
                  : 'border-emerald-500/30 hover:border-emerald-500/50'
              }`}
            >
              <div>
                {/* Card Top Row */}
                <div className="flex items-center justify-between mb-3">
                  <div className="flex items-center gap-2">
                    <Badge
                      variant={
                        rec.priority === 'HIGH' ? 'rose' : rec.priority === 'MEDIUM' ? 'amber' : 'emerald'
                      }
                    >
                      {rec.priority} Priority
                    </Badge>
                  </div>
                  <span className="text-[11px] font-bold px-2 py-0.5 rounded bg-slate-800 text-slate-300">
                    {rec.category}
                  </span>
                </div>
                
                {/* Title */}
                <h3 className="text-lg font-bold text-white mb-2">{rec.title}</h3>

                {/* Problem Identified (Reason) */}
                <div className="mb-3">
                  <div className="text-[10px] uppercase font-bold text-slate-400 tracking-wider mb-1">
                    Data Reason:
                  </div>
                  <p className="text-xs text-slate-300 leading-relaxed font-medium">
                    {rec.reason}
                  </p>
                </div>

                {/* Recommended Suggestion */}
                <div className="p-3.5 rounded-xl bg-slate-950/70 border border-slate-800/80 mb-4">
                  <div className="flex items-center gap-2 text-brand-400 font-bold text-xs mb-1">
                    <Sparkles className="w-3.5 h-3.5" />
                    Recommended Action:
                  </div>
                  <p className="text-xs text-slate-200 leading-relaxed">
                    {rec.action}
                  </p>
                </div>
              </div>

              {/* Card Footer: Source */}
              <div className="pt-3 border-t border-slate-800/80 flex items-center justify-between text-xs">
                <div className="flex items-center gap-1.5 text-slate-400">
                  <Server className="w-3.5 h-3.5" />
                  <span className="font-semibold text-[10px] uppercase">Generated by:</span>
                </div>
                <div className={`font-mono font-bold text-[11px] ${rec.source.includes('Offline') ? 'text-amber-400' : 'text-emerald-400'}`}>
                  {rec.source}
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};
