import React, { useState, useEffect } from 'react';
import { recommendationService } from '../../services/recommendationService';
import { departmentService } from '../../services/departmentService';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { Badge } from '../../components/common/Badge';
import { Sparkles } from 'lucide-react';

export const RecommendationsPage = () => {
  const [recommendations, setRecommendations] = useState([]);
  const [departments, setDepartments] = useState([]);
  const [selectedDept, setSelectedDept] = useState('all');
  const [selectedPriority, setSelectedPriority] = useState('all');
  const [loading, setLoading] = useState(true);

  const loadData = async () => {
    setLoading(true);
    try {
      const [recData, deptData] = await Promise.all([
        recommendationService.getRecommendations(selectedDept),
        departmentService.getDepartments().catch(() => []),
      ]);
      setRecommendations(recData || []);
      setDepartments(deptData || []);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, [selectedDept]);

  const filteredRecs = recommendations.filter((r) => {
    if (selectedPriority !== 'all' && r.priority !== selectedPriority) return false;
    return true;
  });

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <h2 className="text-xl sm:text-2xl font-extrabold text-slate-100 tracking-tight">
              AI Decarbonization Action Recommendations
            </h2>
            <Badge variant="emerald">Prescriptive AI</Badge>
          </div>
          <p className="text-xs text-slate-400 mt-1">
            Prioritized engineering and behavioral interventions generated by analyzing energy anomalies and telemetry.
          </p>
        </div>
      </div>

      {/* Filter Bar */}
      <div className="glass-card rounded-2xl p-4 border border-slate-800 flex flex-wrap items-center justify-between gap-4">
        <div className="flex flex-wrap items-center gap-4">
          <div>
            <label className="block text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-1">
              Filter by Department
            </label>
            <select
              value={selectedDept}
              onChange={(e) => setSelectedDept(e.target.value)}
              className="px-3 py-1.5 rounded-xl bg-slate-950/80 border border-slate-700 text-xs text-slate-200 focus:outline-none focus:border-brand-500 font-semibold"
            >
              <option value="all">All Departments</option>
              {departments.map((d) => (
                <option key={d.id} value={d.id}>
                  {d.name} ({d.code})
                </option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-1">
              Priority Filter
            </label>
            <select
              value={selectedPriority}
              onChange={(e) => setSelectedPriority(e.target.value)}
              className="px-3 py-1.5 rounded-xl bg-slate-950/80 border border-slate-700 text-xs text-slate-200 focus:outline-none focus:border-brand-500 font-semibold"
            >
              <option value="all">All Priorities</option>
              <option value="High">High Priority</option>
              <option value="Medium">Medium Priority</option>
              <option value="Low">Low Priority</option>
            </select>
          </div>
        </div>

        <div className="text-xs text-slate-400">
          Showing <span className="font-bold text-slate-200">{filteredRecs.length}</span> AI Action Cards
        </div>
      </div>

      {loading ? (
        <LoadingSpinner size="lg" text="Synthesizing AI Decarbonization Recommendations..." className="min-h-[40vh]" />
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
          {filteredRecs.map((rec) => (
            <div
              key={rec.id}
              className={`glass-card rounded-2xl p-5 border flex flex-col justify-between transition-all ${
                rec.priority === 'High'
                  ? 'border-rose-500/30 hover:border-rose-500/50 bg-gradient-to-br from-rose-950/10 to-slate-900'
                  : rec.priority === 'Medium'
                  ? 'border-amber-500/30 hover:border-amber-500/50 bg-gradient-to-br from-amber-950/10 to-slate-900'
                  : 'border-emerald-500/30 hover:border-emerald-500/50'
              }`}
            >
              <div>
                {/* Card Top Row */}
                <div className="flex items-center justify-between mb-3">
                  <div className="flex items-center gap-2">
                    <Badge
                      variant={
                        rec.priority === 'High' ? 'rose' : rec.priority === 'Medium' ? 'amber' : 'emerald'
                      }
                    >
                      {rec.priority} Priority
                    </Badge>
                    <span className="text-xs font-semibold text-slate-400 font-mono">
                      {rec.department_name}
                    </span>
                  </div>
                  <span className="text-[11px] font-bold px-2 py-0.5 rounded bg-slate-800 text-slate-300">
                    {rec.category}
                  </span>
                </div>

                {/* Problem Identified */}
                <div className="mb-3">
                  <div className="text-[10px] uppercase font-bold text-slate-400 tracking-wider mb-1">
                    Problem Identified:
                  </div>
                  <p className="text-xs text-slate-300 leading-relaxed font-medium">
                    {rec.problem}
                  </p>
                </div>

                {/* Recommended Suggestion */}
                <div className="p-3.5 rounded-xl bg-slate-950/70 border border-slate-800/80 mb-4">
                  <div className="flex items-center gap-2 text-brand-400 font-bold text-xs mb-1">
                    <Sparkles className="w-3.5 h-3.5" />
                    AI Action Plan:
                  </div>
                  <p className="text-xs text-slate-200 leading-relaxed">
                    {rec.suggestion}
                  </p>
                </div>

                {/* Reasoning */}
                <p className="text-[11px] text-slate-400 italic mb-4 leading-relaxed">
                  " {rec.reasoning} "
                </p>
              </div>

              {/* Card Footer: Impact & Payback */}
              <div className="pt-3 border-t border-slate-800/80 grid grid-cols-2 gap-2 text-xs">
                <div>
                  <div className="text-[10px] text-slate-400 uppercase font-semibold">Expected Impact</div>
                  <div className="font-mono font-bold text-emerald-400 mt-0.5">{rec.expected_impact}</div>
                </div>
                <div className="text-right">
                  <div className="text-[10px] text-slate-400 uppercase font-semibold">Payback / ROI</div>
                  <div className="font-mono font-bold text-cyan-400 mt-0.5">{rec.payback_period}</div>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};
