"""Add carbon calculator run logs

Revision ID: 85291ad815db
Revises: af9daff74393
Create Date: 2026-08-20 18:29:32.098181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85291ad815db'
down_revision: Union[str, Sequence[str], None] = 'af9daff74393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carbon_calculation_run',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('source_dataset_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('records_successful', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('total_emissions_kgco2e', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['data_source.source_dataset_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_carbon_calculation_run_run_id'), 'carbon_calculation_run', ['run_id'], unique=False)
    op.create_table('carbon_calculation_log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('emission_id', sa.Integer(), nullable=True),
    sa.Column('campus_id', sa.Integer(), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('appliance_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('activity_value', sa.Float(), nullable=True),
    sa.Column('activity_unit', sa.String(length=50), nullable=True),
    sa.Column('emission_factor_id', sa.Integer(), nullable=True),
    sa.Column('emission_factor_value', sa.Float(), nullable=True),
    sa.Column('emission_factor_source', sa.String(length=255), nullable=True),
    sa.Column('scope', sa.String(length=50), nullable=True),
    sa.Column('emission_kgco2e', sa.Float(), nullable=True),
    sa.Column('calculation_method', sa.String(length=100), nullable=True),
    sa.Column('calculation_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appliance_id'], ['appliance.appliance_id'], ),
    sa.ForeignKeyConstraint(['building_id'], ['building.building_id'], ),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.campus_id'], ),
    sa.ForeignKeyConstraint(['emission_factor_id'], ['emission_factor.emission_factor_id'], ),
    sa.ForeignKeyConstraint(['emission_id'], ['carbon_emission.emission_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['carbon_calculation_run.run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.zone_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_carbon_calculation_log_log_id'), 'carbon_calculation_log', ['log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carbon_calculation_log_log_id'), table_name='carbon_calculation_log')
    op.drop_table('carbon_calculation_log')
    op.drop_index(op.f('ix_carbon_calculation_run_run_id'), table_name='carbon_calculation_run')
    op.drop_table('carbon_calculation_run')
    # ### end Alembic commands ###
