"""V2 schema

Revision ID: af9daff74393
Revises: 5600fcd09779
Create Date: 2026-08-20 13:26:20.915657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af9daff74393'
down_revision: Union[str, Sequence[str], None] = '5600fcd09779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source',
    sa.Column('source_dataset_id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('license', sa.String(length=100), nullable=True),
    sa.Column('date_imported', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_test_data', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('source_dataset_id')
    )
    op.create_index(op.f('ix_data_source_source_dataset_id'), 'data_source', ['source_dataset_id'], unique=False)
    op.create_table('emission_factor',
    sa.Column('emission_factor_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('activity_unit', sa.String(length=50), nullable=False),
    sa.Column('factor_value', sa.Float(), nullable=False),
    sa.Column('factor_unit', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('emission_factor_id')
    )
    op.create_index(op.f('ix_emission_factor_emission_factor_id'), 'emission_factor', ['emission_factor_id'], unique=False)
    op.create_table('institute',
    sa.Column('institute_id', sa.Integer(), nullable=False),
    sa.Column('institute_name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('institute_id')
    )
    op.create_index(op.f('ix_institute_institute_id'), 'institute', ['institute_id'], unique=False)
    op.create_table('campus',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('institute_id', sa.Integer(), nullable=True),
    sa.Column('campus_name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['institute_id'], ['institute.institute_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campus_id')
    )
    op.create_index(op.f('ix_campus_campus_id'), 'campus', ['campus_id'], unique=False)
    op.create_table('food_consumption',
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('canteen_section', sa.String(length=100), nullable=True),
    sa.Column('food_category', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('source_dataset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['data_source.source_dataset_id'], ),
    sa.PrimaryKeyConstraint('food_id')
    )
    op.create_index(op.f('ix_food_consumption_food_id'), 'food_consumption', ['food_id'], unique=False)
    op.create_table('food_waste',
    sa.Column('waste_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal', sa.String(length=100), nullable=True),
    sa.Column('canteen_section', sa.String(length=100), nullable=True),
    sa.Column('food_category', sa.String(length=100), nullable=True),
    sa.Column('waste_weight_kg', sa.Float(), nullable=True),
    sa.Column('unit_price_per_kg', sa.Float(), nullable=True),
    sa.Column('cost_loss', sa.Float(), nullable=True),
    sa.Column('carbon_emission_kgco2e', sa.Float(), nullable=True),
    sa.Column('source_dataset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['data_source.source_dataset_id'], ),
    sa.PrimaryKeyConstraint('waste_id')
    )
    op.create_index(op.f('ix_food_waste_date'), 'food_waste', ['date'], unique=False)
    op.create_index(op.f('ix_food_waste_waste_id'), 'food_waste', ['waste_id'], unique=False)
    op.create_table('sustainability_profile',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('clothing_spend_month', sa.Float(), nullable=True),
    sa.Column('food_type', sa.String(length=100), nullable=True),
    sa.Column('housing_type', sa.String(length=100), nullable=True),
    sa.Column('energy_usage_kwh_month', sa.Float(), nullable=True),
    sa.Column('water_usage_liters_day', sa.Float(), nullable=True),
    sa.Column('transportation_mode', sa.String(length=100), nullable=True),
    sa.Column('consumption_spend_month', sa.Float(), nullable=True),
    sa.Column('recycling_habits', sa.String(length=100), nullable=True),
    sa.Column('carbon_emissions_kgco2', sa.Float(), nullable=True),
    sa.Column('source_dataset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['data_source.source_dataset_id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index(op.f('ix_sustainability_profile_profile_id'), 'sustainability_profile', ['profile_id'], unique=False)
    op.create_table('building',
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=True),
    sa.Column('building_name', sa.String(length=255), nullable=False),
    sa.Column('building_type', sa.String(length=100), nullable=True),
    sa.Column('floor_count', sa.Integer(), nullable=True),
    sa.Column('built_up_area', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.campus_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('building_id')
    )
    op.create_index(op.f('ix_building_building_id'), 'building', ['building_id'], unique=False)
    op.create_table('solar_site',
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=True),
    sa.Column('site_name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.campus_id'], ),
    sa.PrimaryKeyConstraint('site_id')
    )
    op.create_index(op.f('ix_solar_site_site_id'), 'solar_site', ['site_id'], unique=False)
    op.create_table('transport_activity',
    sa.Column('transport_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('campus_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('transport_mode', sa.String(length=100), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('passenger_count', sa.Integer(), nullable=True),
    sa.Column('fuel_type', sa.String(length=100), nullable=True),
    sa.Column('source_dataset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.campus_id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['sustainability_profile.profile_id'], ),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['data_source.source_dataset_id'], ),
    sa.PrimaryKeyConstraint('transport_id')
    )
    op.create_index(op.f('ix_transport_activity_transport_id'), 'transport_activity', ['transport_id'], unique=False)
    op.create_table('energy_consumption',
    sa.Column('energy_id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('campus_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('energy_source', sa.String(length=100), nullable=True),
    sa.Column('consumption_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('source_dataset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['building.building_id'], ),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.campus_id'], ),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['data_source.source_dataset_id'], ),
    sa.PrimaryKeyConstraint('energy_id')
    )
    op.create_index(op.f('ix_energy_consumption_energy_id'), 'energy_consumption', ['energy_id'], unique=False)
    op.create_index(op.f('ix_energy_consumption_timestamp'), 'energy_consumption', ['timestamp'], unique=False)
    op.create_table('solar_generation',
    sa.Column('solar_record_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=50), nullable=False),
    sa.Column('data_status', sa.Boolean(), nullable=True),
    sa.Column('average_generation', sa.Float(), nullable=True),
    sa.Column('maximum_generation', sa.Float(), nullable=True),
    sa.Column('minimum_generation', sa.Float(), nullable=True),
    sa.Column('generation_unit', sa.String(length=50), nullable=True),
    sa.Column('source_dataset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['solar_site.site_id'], ),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['data_source.source_dataset_id'], ),
    sa.PrimaryKeyConstraint('solar_record_id')
    )
    op.create_index(op.f('ix_solar_generation_solar_record_id'), 'solar_generation', ['solar_record_id'], unique=False)
    op.create_table('waste_generation',
    sa.Column('waste_id', sa.Integer(), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('waste_type', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('disposal_method', sa.String(length=100), nullable=True),
    sa.Column('source_dataset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['building.building_id'], ),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.campus_id'], ),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['data_source.source_dataset_id'], ),
    sa.PrimaryKeyConstraint('waste_id')
    )
    op.create_index(op.f('ix_waste_generation_waste_id'), 'waste_generation', ['waste_id'], unique=False)
    op.create_table('water_consumption',
    sa.Column('water_id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('campus_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('consumption_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('source_dataset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['building.building_id'], ),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.campus_id'], ),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['data_source.source_dataset_id'], ),
    sa.PrimaryKeyConstraint('water_id')
    )
    op.create_index(op.f('ix_water_consumption_water_id'), 'water_consumption', ['water_id'], unique=False)
    op.create_table('zone',
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('zone_name', sa.String(length=255), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=True),
    sa.Column('zone_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['building.building_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('zone_id')
    )
    op.create_index(op.f('ix_zone_zone_id'), 'zone', ['zone_id'], unique=False)
    op.create_table('appliance',
    sa.Column('appliance_id', sa.Integer(), nullable=False),
    sa.Column('appliance_name', sa.String(length=255), nullable=False),
    sa.Column('appliance_type', sa.String(length=100), nullable=True),
    sa.Column('rated_power_kw', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['building.building_id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.zone_id'], ),
    sa.PrimaryKeyConstraint('appliance_id')
    )
    op.create_index(op.f('ix_appliance_appliance_id'), 'appliance', ['appliance_id'], unique=False)
    op.create_table('appliance_usage',
    sa.Column('usage_id', sa.Integer(), nullable=False),
    sa.Column('appliance_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('power_kw', sa.Float(), nullable=True),
    sa.Column('energy_kwh', sa.Float(), nullable=True),
    sa.Column('source_dataset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['appliance_id'], ['appliance.appliance_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['data_source.source_dataset_id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.zone_id'], ),
    sa.PrimaryKeyConstraint('usage_id')
    )
    op.create_index(op.f('ix_appliance_usage_timestamp'), 'appliance_usage', ['timestamp'], unique=False)
    op.create_index(op.f('ix_appliance_usage_usage_id'), 'appliance_usage', ['usage_id'], unique=False)
    op.create_table('carbon_emission',
    sa.Column('emission_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('appliance_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('scope', sa.String(length=50), nullable=True),
    sa.Column('activity_value', sa.Float(), nullable=True),
    sa.Column('activity_unit', sa.String(length=50), nullable=True),
    sa.Column('emission_factor_id', sa.Integer(), nullable=True),
    sa.Column('emission_factor_value', sa.Float(), nullable=True),
    sa.Column('emission_kgco2e', sa.Float(), nullable=True),
    sa.Column('calculation_method', sa.String(length=100), nullable=True),
    sa.Column('source_dataset_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appliance_id'], ['appliance.appliance_id'], ),
    sa.ForeignKeyConstraint(['building_id'], ['building.building_id'], ),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.campus_id'], ),
    sa.ForeignKeyConstraint(['emission_factor_id'], ['emission_factor.emission_factor_id'], ),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['data_source.source_dataset_id'], ),
    sa.PrimaryKeyConstraint('emission_id')
    )
    op.create_index(op.f('ix_carbon_emission_date'), 'carbon_emission', ['date'], unique=False)
    op.create_index(op.f('ix_carbon_emission_emission_id'), 'carbon_emission', ['emission_id'], unique=False)
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_infrastructure_data_id'), table_name='infrastructure_data')
    op.drop_table('infrastructure_data')
    op.drop_index(op.f('ix_water_data_id'), table_name='water_data')
    op.drop_table('water_data')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_carbon_calculations_id'), table_name='carbon_calculations')
    op.drop_table('carbon_calculations')
    op.drop_index(op.f('ix_electricity_data_id'), table_name='electricity_data')
    op.drop_table('electricity_data')
    op.drop_index(op.f('ix_transportation_data_id'), table_name='transportation_data')
    op.drop_table('transportation_data')
    op.drop_index(op.f('ix_simulations_id'), table_name='simulations')
    op.drop_table('simulations')
    op.drop_index(op.f('ix_appliances_id'), table_name='appliances')
    op.drop_table('appliances')
    op.drop_index(op.f('ix_uploaded_documents_id'), table_name='uploaded_documents')
    op.drop_table('uploaded_documents')
    op.drop_index(op.f('ix_emission_factors_category'), table_name='emission_factors')
    op.drop_index(op.f('ix_emission_factors_id'), table_name='emission_factors')
    op.drop_table('emission_factors')
    op.drop_index(op.f('ix_waste_data_id'), table_name='waste_data')
    op.drop_table('waste_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waste_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('waste_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('weight_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_recycled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('waste_data_department_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('waste_data_pkey'))
    )
    op.create_index(op.f('ix_waste_data_id'), 'waste_data', ['id'], unique=False)
    op.create_table('emission_factors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('subcategory', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('activity_unit', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('factor_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('factor_unit', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('valid_from', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('valid_to', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('emission_factors_pkey'))
    )
    op.create_index(op.f('ix_emission_factors_id'), 'emission_factors', ['id'], unique=False)
    op.create_index(op.f('ix_emission_factors_category'), 'emission_factors', ['category'], unique=False)
    op.create_table('uploaded_documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('storage_reference', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('processing_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('uploaded_documents_uploaded_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('uploaded_documents_pkey'))
    )
    op.create_index(op.f('ix_uploaded_documents_id'), 'uploaded_documents', ['id'], unique=False)
    op.create_table('appliances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('power_rating_kw', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('appliances_department_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('appliances_pkey'))
    )
    op.create_index(op.f('ix_appliances_id'), 'appliances', ['id'], unique=False)
    op.create_table('simulations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('result_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('simulations_pkey'))
    )
    op.create_index(op.f('ix_simulations_id'), 'simulations', ['id'], unique=False)
    op.create_table('transportation_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vehicle_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('fuel_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('distance_or_fuel_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('transportation_data_department_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('transportation_data_pkey'))
    )
    op.create_index(op.f('ix_transportation_data_id'), 'transportation_data', ['id'], unique=False)
    op.create_table('electricity_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kwh', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('electricity_data_department_id_fkey')),
    sa.ForeignKeyConstraint(['document_id'], ['uploaded_documents.id'], name=op.f('electricity_data_document_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('electricity_data_pkey'))
    )
    op.create_index(op.f('ix_electricity_data_id'), 'electricity_data', ['id'], unique=False)
    op.create_table('carbon_calculations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('activity_record_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('factor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('calculated_emission', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('calculation_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('carbon_calculations_department_id_fkey')),
    sa.ForeignKeyConstraint(['factor_id'], ['emission_factors.id'], name=op.f('carbon_calculations_factor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('carbon_calculations_pkey'))
    )
    op.create_index(op.f('ix_carbon_calculations_id'), 'carbon_calculations', ['id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('result_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('predictions_pkey'))
    )
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('report_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reporting_period', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_reference', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('reports_created_by_fkey')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('reports_department_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reports_pkey'))
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_table('water_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('liters_consumed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('water_data_department_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('water_data_pkey'))
    )
    op.create_index(op.f('ix_water_data_id'), 'water_data', ['id'], unique=False)
    op.create_table('infrastructure_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('infrastructure_data_department_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('infrastructure_data_pkey'))
    )
    op.create_index(op.f('ix_infrastructure_data_id'), 'infrastructure_data', ['id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('problem', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('suggestion', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expected_impact', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('recommendations_department_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('recommendations_pkey'))
    )
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.drop_index(op.f('ix_carbon_emission_emission_id'), table_name='carbon_emission')
    op.drop_index(op.f('ix_carbon_emission_date'), table_name='carbon_emission')
    op.drop_table('carbon_emission')
    op.drop_index(op.f('ix_appliance_usage_usage_id'), table_name='appliance_usage')
    op.drop_index(op.f('ix_appliance_usage_timestamp'), table_name='appliance_usage')
    op.drop_table('appliance_usage')
    op.drop_index(op.f('ix_appliance_appliance_id'), table_name='appliance')
    op.drop_table('appliance')
    op.drop_index(op.f('ix_zone_zone_id'), table_name='zone')
    op.drop_table('zone')
    op.drop_index(op.f('ix_water_consumption_water_id'), table_name='water_consumption')
    op.drop_table('water_consumption')
    op.drop_index(op.f('ix_waste_generation_waste_id'), table_name='waste_generation')
    op.drop_table('waste_generation')
    op.drop_index(op.f('ix_solar_generation_solar_record_id'), table_name='solar_generation')
    op.drop_table('solar_generation')
    op.drop_index(op.f('ix_energy_consumption_timestamp'), table_name='energy_consumption')
    op.drop_index(op.f('ix_energy_consumption_energy_id'), table_name='energy_consumption')
    op.drop_table('energy_consumption')
    op.drop_index(op.f('ix_transport_activity_transport_id'), table_name='transport_activity')
    op.drop_table('transport_activity')
    op.drop_index(op.f('ix_solar_site_site_id'), table_name='solar_site')
    op.drop_table('solar_site')
    op.drop_index(op.f('ix_building_building_id'), table_name='building')
    op.drop_table('building')
    op.drop_index(op.f('ix_sustainability_profile_profile_id'), table_name='sustainability_profile')
    op.drop_table('sustainability_profile')
    op.drop_index(op.f('ix_food_waste_waste_id'), table_name='food_waste')
    op.drop_index(op.f('ix_food_waste_date'), table_name='food_waste')
    op.drop_table('food_waste')
    op.drop_index(op.f('ix_food_consumption_food_id'), table_name='food_consumption')
    op.drop_table('food_consumption')
    op.drop_index(op.f('ix_campus_campus_id'), table_name='campus')
    op.drop_table('campus')
    op.drop_index(op.f('ix_institute_institute_id'), table_name='institute')
    op.drop_table('institute')
    op.drop_index(op.f('ix_emission_factor_emission_factor_id'), table_name='emission_factor')
    op.drop_table('emission_factor')
    op.drop_index(op.f('ix_data_source_source_dataset_id'), table_name='data_source')
    op.drop_table('data_source')
    # ### end Alembic commands ###
